workflows:
    ios-workflow:
        name: Cats and Modules Workflow
        max_build_duration: 120
        environment:
            groups:
                - firebase_credentials
            ios_signing:
                distribution_type: development
                bundle_identifier: ua.edu.ukma.apple-env.verkhohliad.CatsUI
            vars:
                BUNDLE_ID: "io.codemagic.sample.iosnative"
                XCODE_WORKSPACE: "CatsAndModules_KaterynaVerkhohliad.xcworkspace"
                XCODE_SCHEME: "CatsUI"
        scripts:
            - name: Set up code signing settings on Xcode project
              script: |
                xcode-project use-profiles
            - name: Load Firebase configuration
              script: | 
                # set -e # exit on first failed command
                # echo $IOS_FIREBASE_SECRET > $CM_BUILD_DIR/GoogleService-Info.plist
            - name: Build ipa for distribution
              script: | 
                xcode-project build-ipa \
                    --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
                    --scheme "$XCODE_SCHEME"
    publishing:
        email:
            recipients:
                - verkhogliadkate@gmail.com
        notify:
            success: true
            failure: false