workflows:
    ios-workflow:
        name: Cats and Modules Workflow
        max_build_duration: 120
        environment:
            groups:
                - firebase_credentials
            ios_signing:
                distribution_type: development
                bundle_identifier: ua.edu.ukma.apple-env.verkhohliad.CatsUI
            vars:
                BUNDLE_ID: "io.codemagic.sample.iosnative"
                XCODE_WORKSPACE: "CatsAndModules_KaterynaVerkhohliad.xcworkspace"
                XCODE_SCHEME: "CatsUI"
        scripts:
            - name: Create GoogleService-Info.plist from environment variable
              script: |
                echo $IOS_FIREBASE_SECRET | base64 --decode > /Users/builder/GoogleService-Info.plist
                ls $CM_BUILD_DIR/$XCODE_WORKSPACE
            - name: Set up code signing settings on Xcode project
              script: |
                xcode-project use-profiles
            - name: Build ipa for distribution
              script: | 
                xcode-project build-ipa \
                    --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
                    --scheme "$XCODE_SCHEME"
