workflows:
    ios-workflow:
        name: Cats and Modules Workflow
        max_build_duration: 120
        environment:
            groups:
                - firebase_credentials
            ios_signing:
                distribution_type: development
                bundle_identifier: ua.edu.ukma.apple-env.verkhohliad.CatsUI
            vars:
                BUNDLE_ID: "io.codemagic.sample.iosnative"
                XCODE_WORKSPACE: "CatsAndModules_KaterynaVerkhohliad.xcworkspace"
                XCODE_SCHEME: "CatsUI"
        scripts:
            - name: Create GoogleService-Info.plist from environment variable
              script: |
                echo $IOS_FIREBASE_SECRET | base64 --decode > /Users/builder/GoogleService-Info.plist
            - name: Set up code signing settings on Xcode project
              script: |
                xcode-project use-profiles
            - name: Set the build version
              script: | 
                set -e
                set -x
                cd $CM_BUILD_DIR
                agvtool new-version -all $(($BUILD_NUMBER + 1))               
            - name: Build ipa for distribution
              script: | 
                xcode-project build-ipa \
                    --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
                    --scheme "$XCODE_SCHEME"
        publishing:
            firebase:
                firebase_service_account: $FIREBASE_SERVICE_ACCOUNT

                ios:
                    app_id: 1:196550812672:ios:4042484c0cd975b616e4e5
                    groups:
                      - naukma
