# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build_and_export do
    increment_version_number(
      bump_type: "minor",
      xcodeproj: "./CatsUI/CatsUI.xcodeproj"
    )
    gym
    firebase_app_distribution(
      service_credentials_file: "../catsandmodulesverkhohliad-29c260cf1ac3.json",
      ipa_path: "./output/CatsApp.ipa",
      release_notes: "My wonderful fastlane release",
      testers: "o.frankiv@ukma.edu.ua"
    )
  end

  lane :take_screenshots do
    capture_screenshots
  end
end
